'use strict';
const canvas = document.querySelector('#game'), ctx = canvas.getContext('2d'), mini = document.querySelector('#mini'), mc = mini.getContext('2d');
const $ = id => document.getElementById(id), W = 2400, H = 1600, CW = 1100, CH = 650;
const weapons = { rifle: { name: 'ASSAULT RIFLE', mag: 30, reserve: 180, damage: 24, rate: .115, reload: 1.7, speed: 1250, spread: .055, range: 1050, auto: true }, pistol: { name: 'PISTOL', mag: 12, reserve: 72, damage: 34, rate: .27, reload: 1.15, speed: 1100, spread: .025, range: 850, auto: false } };
const keys = {}, mouse = { x: 550, y: 325, down: false }, camera = { x: 0, y: 0 };
let soldiers = [], bullets = [], effects = [], walls = [], decor = [], scores = { blue: 0, red: 0 }, remaining = 600, mode = 'menu', last = 0, shotHeld = false, feed = [], hitTime = 0, mapName = 'urban', difficulty = 'normal';
const rand = (a, b) => a + Math.random() * (b - a), clamp = (x, a, b) => Math.max(a, Math.min(b, x));
const color = t => t === 'blue' ? '#4aace8' : '#e96c65';
function makeSoldier(id, team, human = false) { return { id, team, human, x: 0, y: 0, r: 15, hp: 100, armor: 50, angle: 0, aim: 0, vx: 0, vy: 0, walk: 0, gun: 'rifle', inventory: { rifle: { ammo: 30, reserve: 180 }, pistol: { ammo: 12, reserve: 72 } }, cool: 0, reload: 0, dead: 0, invuln: 0, kills: 0, deaths: 0, target: null, path: [], pathTimer: 0, think: 0, strafe: Math.random() < .5 ? -1 : 1 }; }
const player = makeSoldier('YOU', 'blue', true);
function wall(x, y, w, h, type = 'concrete') { walls.push({ x, y, w, h, type }); }
function createMap() {
    walls = []; decor = []; wall(0, 0, W, 38); wall(0, H - 38, W, 38); wall(0, 0, 38, H); wall(W - 38, 0, 38, H);
    const urban = mapName === 'urban';
    [[420, 180, 330, 260], [1040, 160, 310, 290], [1650, 180, 330, 260], [420, 1150, 330, 260], [1040, 1150, 310, 290], [1650, 1150, 330, 260]].forEach(v => wall(...v, urban ? 'building' : 'sandstone'));
    [[630, 600, 190, 36], [920, 900, 180, 36], [1340, 600, 190, 36], [1670, 900, 180, 36], [820, 470, 38, 150], [1540, 1000, 38, 150], [300, 960, 140, 35], [1980, 610, 140, 35], [1080, 760, 170, 38]].forEach(v => wall(...v));
    [[870, 580], [940, 580], [1410, 970], [1480, 970], [600, 960], [1770, 540], [1170, 620], [1250, 990], [760, 1050], [1600, 480]].forEach(v => wall(v[0], v[1], 56, 56, 'crate'));
    for (let i = 0; i < 90; i++) { const x = rand(80, W - 80), y = rand(80, H - 80); if (!blocked(x, y, 23)) decor.push({ x, y, r: rand(5, 15), type: urban ? 'tree' : 'bush' }); }
}
function collide(x, y, r, o) { let cx = clamp(x, o.x, o.x + o.w), cy = clamp(y, o.y, o.y + o.h); return (x - cx) ** 2 + (y - cy) ** 2 < r * r; }
function blocked(x, y, r) { return walls.some(w => collide(x, y, r, w)); }
function move(s, dx, dy) { const ox = s.x, oy = s.y; if (!blocked(s.x + dx, s.y, s.r)) s.x += dx; if (!blocked(s.x, s.y + dy, s.r)) s.y += dy; for (const o of soldiers) { if (o === s || o.hp <= 0) continue; let vx = s.x - o.x, vy = s.y - o.y, d = Math.hypot(vx, vy); if (d > 0 && d < s.r + o.r) { s.x = ox; s.y = oy; break; } } const d = Math.hypot(s.x - ox, s.y - oy); if (d > .01) s.walk += d * .09; return d; }
function spawn(s) { let left = s.team === 'blue'; for (let i = 0; i < 50; i++) { let x = left ? rand(100, 320) : rand(2080, 2290), y = rand(510, 1080); if (!blocked(x, y, 24) && soldiers.every(o => o === s || o.hp <= 0 || Math.hypot(o.x - x, o.y - y) > 42)) { s.x = x; s.y = y; break; } } s.hp = 100; s.armor = 50; s.dead = 0; s.invuln = 1.8; s.vx = s.vy = 0; s.reload = 0; s.cool = 0; s.path = []; for (const [k, w] of Object.entries(weapons)) s.inventory[k] = { ammo: w.mag, reserve: w.reserve }; }
function start() { mapName = $('mapChoice').value; difficulty = $('difficulty').value; scores = { blue: 0, red: 0 }; remaining = 600; bullets = []; effects = []; feed = []; soldiers = [player]; player.kills = 0; player.deaths = 0; player.gun = 'rifle'; for (let i = 1; i <= 4; i++)soldiers.push(makeSoldier('BLUE ' + i, 'blue')); for (let i = 1; i <= 5; i++)soldiers.push(makeSoldier('RED ' + i, 'red')); createMap(); for (const s of soldiers) spawn(s); mode = 'playing'; $('menu').classList.add('hidden'); $('results').classList.add('hidden'); $('pause').classList.add('hidden'); $('hud').classList.remove('hidden'); $('scoreboard').classList.add('hidden'); mouse.down = false; }
function gun(s) { return weapons[s.gun]; } function ammo(s) { return s.inventory[s.gun]; }
function reload(s) { if (s.hp <= 0 || s.reload > 0) return; const a = ammo(s), w = gun(s); if (a.ammo < w.mag && a.reserve > 0) s.reload = w.reload; }
function switchGun(s, k) { if (!weapons[k] || s.gun === k) return; s.gun = k; s.reload = 0; s.cool = .22; }
function fire(s) { const w = gun(s), a = ammo(s); if (s.hp <= 0 || s.cool > 0 || s.reload > 0 || mode !== 'playing') return; if (a.ammo <= 0) { reload(s); return; } a.ammo--; s.cool = w.rate; const movement = Math.hypot(s.vx, s.vy), spread = w.spread * (1 + movement / 200); const ang = s.angle + rand(-spread, spread); const x = s.x + Math.cos(ang) * 29, y = s.y + Math.sin(ang) * 29; bullets.push({ x, y, px: x, py: y, vx: Math.cos(ang) * w.speed, vy: Math.sin(ang) * w.speed, team: s.team, owner: s, damage: w.damage, life: w.range / w.speed, range: w.range, traveled: 0 }); effects.push({ x, y, t: .09, type: 'flash' }); }
function lineOfSight(a, b) { const d = Math.hypot(b.x - a.x, b.y - a.y), n = Math.ceil(d / 16); for (let i = 1; i < n; i++) { const t = i / n; if (blocked(a.x + (b.x - a.x) * t, a.y + (b.y - a.y) * t, 3)) return false; } return true; }
// Navigation grid with A* pathfinding for bots.
const CELL = 80, COLS = Math.ceil(W / CELL), ROWS = Math.ceil(H / CELL);
function gridIndex(x, y) { return clamp(Math.floor(y / CELL), 0, ROWS - 1) * COLS + clamp(Math.floor(x / CELL), 0, COLS - 1); }
function gridPoint(i) { return { x: (i % COLS + .5) * CELL, y: (Math.floor(i / COLS) + .5) * CELL }; }
function pathfind(from, to) { const start = gridIndex(from.x, from.y), goal = gridIndex(to.x, to.y), open = [start], came = new Map(), g = new Map([[start, 0]]), f = new Map([[start, 0]]), seen = new Set(); let count = 0; while (open.length && count++ < 700) { open.sort((a, b) => (f.get(a) ?? Infinity) - (f.get(b) ?? Infinity)); const cur = open.shift(); if (cur === goal) { const result = []; let p = cur; while (came.has(p)) { result.unshift(gridPoint(p)); p = came.get(p); } return result; } seen.add(cur); const x = cur % COLS, y = Math.floor(cur / COLS); for (const [dx, dy] of [[1, 0], [-1, 0], [0, 1], [0, -1]]) { const nx = x + dx, ny = y + dy; if (nx < 0 || ny < 0 || nx >= COLS || ny >= ROWS) continue; const ni = ny * COLS + nx, pt = gridPoint(ni); if (seen.has(ni) || blocked(pt.x, pt.y, 21)) continue; const tentative = (g.get(cur) ?? Infinity) + 1; if (tentative < (g.get(ni) ?? Infinity)) { came.set(ni, cur); g.set(ni, tentative); f.set(ni, tentative + Math.abs(nx - goal % COLS) + Math.abs(ny - Math.floor(goal / COLS))); if (!open.includes(ni)) open.push(ni); } } } return []; }
function nearestEnemy(s) { let best = null, d = Infinity; for (const o of soldiers) { if (o.team === s.team || o.hp <= 0) continue; const n = Math.hypot(o.x - s.x, o.y - s.y); if (n < d) { d = n; best = o; } } return best; }
function botUpdate(s, dt) {
    s.think -= dt; s.pathTimer -= dt; if (s.think <= 0 || !s.target || s.target.hp <= 0) { s.target = nearestEnemy(s); s.think = .25; } if (!s.target) return; const t = s.target, dx = t.x - s.x, dy = t.y - s.y, d = Math.hypot(dx, dy), visible = d < 800 && lineOfSight(s, t); const reaction = { easy: .18, normal: .10, hard: .05 }[difficulty]; s.aim += clamp(Math.atan2(Math.sin(Math.atan2(dy, dx) - s.aim), Math.cos(Math.atan2(dy, dx) - s.aim)), -dt * (reaction ? 7 : 10), dt * 7); s.angle = s.aim; let mx = 0, my = 0;
    if (visible && d < 650) { if (d > 320) { mx = dx / d; my = dy / d; } else if (d < 160) { mx = -dx / d; my = -dy / d; } else { mx = -dy / d * s.strafe * .7; my = dx / d * s.strafe * .7; } if (s.cool <= 0 && Math.random() < ({ easy: .35, normal: .75, hard: .96 }[difficulty])) fire(s); } else { if (s.pathTimer <= 0) { s.path = pathfind(s, t); s.pathTimer = rand(.9, 1.6); } while (s.path.length && Math.hypot(s.path[0].x - s.x, s.path[0].y - s.y) < 27) s.path.shift(); const p = s.path[0] || t; const a = Math.atan2(p.y - s.y, p.x - s.x); mx = Math.cos(a); my = Math.sin(a); }
    const speed = { easy: 100, normal: 135, hard: 160 }[difficulty]; s.vx = mx * speed; s.vy = my * speed; const moved = move(s, s.vx * dt, s.vy * dt); if (moved < .05 && d > 90) { s.pathTimer = 0; s.strafe *= -1; } if (ammo(s).ammo === 0) reload(s);
}
function playerUpdate(dt) { let x = Number(!!keys.d) - Number(!!keys.a), y = Number(!!keys.s) - Number(!!keys.w), d = Math.hypot(x, y) || 1; let speed = keys.control ? 105 : keys.shift ? 320 : 220; const targetX = x / d * speed, targetY = y / d * speed; const factor = Math.min(1, dt * 13); player.vx += (targetX - player.vx) * factor; player.vy += (targetY - player.vy) * factor; move(player, player.vx * dt, player.vy * dt); player.angle = Math.atan2(mouse.y + camera.y - player.y, mouse.x + camera.x - player.x); if (mouse.down && (!shotHeld || gun(player).auto)) fire(player); shotHeld = mouse.down; }
function eliminate(s, attacker) { s.hp = 0; s.dead = 3; s.deaths++; if (attacker && attacker !== s) { attacker.kills++; scores[attacker.team]++; feed.unshift({ text: attacker.id + '  →  ' + s.id, team: attacker.team, time: 4 }); feed = feed.slice(0, 5); } if (scores.blue >= 50 || scores.red >= 50) finish(); }
function bulletUpdate(dt) { for (let i = bullets.length - 1; i >= 0; i--) { const b = bullets[i]; let hit = false; const n = Math.max(1, Math.ceil(Math.hypot(b.vx, b.vy) * dt / 8)); b.px = b.x; b.py = b.y; for (let j = 0; j < n; j++) { const stepX = b.vx * dt / n, stepY = b.vy * dt / n; b.x += stepX; b.y += stepY; b.traveled += Math.hypot(stepX, stepY); if (blocked(b.x, b.y, 3)) { hit = true; effects.push({ x: b.x, y: b.y, t: .16, type: 'impact' }); break; } for (const s of soldiers) { if (s.team === b.team || s.hp <= 0 || s.invuln > 0) continue; if (Math.hypot(s.x - b.x, s.y - b.y) < s.r + 3) { let damage = b.damage * (1 - .35 * clamp(b.traveled / b.range, 0, 1)); const absorbed = Math.min(s.armor, damage * .4); s.armor -= absorbed; s.hp = Math.max(0, s.hp - Math.ceil(damage - absorbed)); if (b.owner === player) hitTime = .13; effects.push({ x: b.x, y: b.y, t: .16, type: 'hit' }); if (s.hp === 0) eliminate(s, b.owner); hit = true; break; } } if (hit) break; } b.life -= dt; if (hit || b.life <= 0) bullets.splice(i, 1); } }
function finish() { if (mode !== 'playing') return; mode = 'results'; $('results').classList.remove('hidden'); $('resultTitle').textContent = scores.blue === scores.red ? 'DRAW' : scores.blue > scores.red ? 'BLUE TEAM WINS' : 'RED TEAM WINS'; const mvp = [...soldiers].sort((a, b) => b.kills - a.kills)[0]; $('resultStats').textContent = `Blue ${scores.blue} - ${scores.red} Red | Your kills: ${player.kills} | Deaths: ${player.deaths} | MVP: ${mvp.id} (${mvp.kills} kills)`; mouse.down = false; }
function update(dt) { remaining = Math.max(0, remaining - dt); if (!remaining) { finish(); return; } for (const s of soldiers) { if (s.hp <= 0) { s.dead -= dt; if (s.dead <= 0) spawn(s); continue; } s.cool = Math.max(0, s.cool - dt); s.invuln = Math.max(0, s.invuln - dt); if (s.reload > 0) { s.reload -= dt; if (s.reload <= 0) { const a = ammo(s), w = gun(s), n = Math.min(w.mag - a.ammo, a.reserve); a.ammo += n; a.reserve -= n; s.reload = 0; } } if (s.human) playerUpdate(dt); else botUpdate(s, dt); } bulletUpdate(dt); effects = effects.filter(e => (e.t -= dt) > 0); feed = feed.filter(e => (e.time -= dt) > 0); hitTime = Math.max(0, hitTime - dt); camera.x = clamp(player.x - CW / 2, 0, W - CW); camera.y = clamp(player.y - CH / 2, 0, H - CH); hud(); }
function hud() { const a = ammo(player); $('blueScore').textContent = 'BLUE ' + scores.blue; $('redScore').textContent = 'RED ' + scores.red; const sec = Math.ceil(remaining); $('clock').textContent = `${Math.floor(sec / 60)}:${String(sec % 60).padStart(2, '0')}`; $('hp').textContent = Math.ceil(player.hp); $('armor').textContent = Math.ceil(player.armor); $('healthFill').style.width = player.hp + '%'; $('weapon').textContent = gun(player).name; $('ammo').textContent = a.ammo + ' / ' + a.reserve; $('reload').textContent = player.reload > 0 ? 'RELOADING ' + Math.ceil(player.reload * 10) / 10 + 's' : 'R TO RELOAD'; $('feed').innerHTML = feed.map(f => `<div style="color:${color(f.team)}">${f.text}</div>`).join(''); $('respawn').textContent = player.hp <= 0 ? 'RESPAWNING ' + Math.ceil(player.dead) : ''; $('hitmarker').textContent = hitTime > 0 ? '✕' : ''; }
function drawMap() {
    ctx.fillStyle = mapName === 'urban' ? '#667269' : '#ad9c78'; ctx.fillRect(0, 0, W, H); ctx.strokeStyle = '#0000000b'; ctx.lineWidth = 1; for (let x = 0; x < W; x += 80) { ctx.beginPath(); ctx.moveTo(x, 0); ctx.lineTo(x, H); ctx.stroke(); } for (let y = 0; y < H; y += 80) { ctx.beginPath(); ctx.moveTo(0, y); ctx.lineTo(W, y); ctx.stroke(); } ctx.fillStyle = mapName === 'urban' ? '#454d4c' : '#988b6c'; ctx.fillRect(0, 715, W, 170); ctx.fillRect(1120, 0, 160, H); ctx.strokeStyle = '#d7cda0'; ctx.lineWidth = 3; ctx.setLineDash([35, 30]); ctx.beginPath(); ctx.moveTo(0, 800); ctx.lineTo(W, 800); ctx.moveTo(1200, 0); ctx.lineTo(1200, H); ctx.stroke(); ctx.setLineDash([]);
    for (const d of decor) { ctx.fillStyle = '#0002'; ctx.beginPath(); ctx.ellipse(d.x + 5, d.y + 6, d.r + 3, d.r * .7, 0, 0, 7); ctx.fill(); ctx.fillStyle = d.type === 'tree' ? '#3b674b' : '#827a50'; ctx.beginPath(); ctx.arc(d.x, d.y, d.r, 0, 7); ctx.fill(); ctx.strokeStyle = '#ffffff20'; ctx.stroke(); }
    for (const w of walls) { ctx.fillStyle = '#0004'; ctx.fillRect(w.x + 7, w.y + 8, w.w, w.h); ctx.fillStyle = w.type === 'building' ? '#818c87' : w.type === 'sandstone' ? '#b8a77f' : w.type === 'crate' ? '#a0794d' : '#9aa4a1'; ctx.fillRect(w.x, w.y, w.w, w.h); ctx.strokeStyle = w.type === 'crate' ? '#674b2c' : '#d0d6cf'; ctx.lineWidth = w.type === 'building' ? 5 : 3; ctx.strokeRect(w.x + 2, w.y + 2, w.w - 4, w.h - 4); if (w.type === 'building' || w.type === 'sandstone') { ctx.fillStyle = '#0002'; ctx.fillRect(w.x + 30, w.y + 30, 80, 50); ctx.fillRect(w.x + w.w - 100, w.y + 40, 65, 45); } if (w.type === 'crate') { ctx.strokeStyle = '#6c4c30'; ctx.beginPath(); ctx.moveTo(w.x + 4, w.y + 4); ctx.lineTo(w.x + w.w - 4, w.y + w.h - 4); ctx.moveTo(w.x + w.w - 4, w.y + 4); ctx.lineTo(w.x + 4, w.y + w.h - 4); ctx.stroke(); } }
}
function drawSoldier(s) { if (s.hp <= 0) return; ctx.save(); ctx.translate(s.x, s.y); ctx.rotate(s.angle); const walk = Math.sin(s.walk) * 5, team = color(s.team); ctx.fillStyle = '#0004'; ctx.beginPath(); ctx.ellipse(3, 5, 22, 18, 0, 0, 7); ctx.fill(); ctx.fillStyle = '#202a28'; ctx.fillRect(-15 + walk, -12, 15, 9); ctx.fillRect(-15 - walk, 4, 15, 9); ctx.fillStyle = '#111919'; ctx.fillRect(-18 + walk, -12, 9, 9); ctx.fillRect(-18 - walk, 4, 9, 9); ctx.fillStyle = '#424d43'; ctx.fillRect(0, -18, 22, 9); ctx.fillRect(0, 9, 22, 9); ctx.fillStyle = team; ctx.beginPath(); ctx.roundRect(-13, -14, 28, 28, 5); ctx.fill(); ctx.strokeStyle = '#202726'; ctx.lineWidth = 3; ctx.stroke(); ctx.fillStyle = '#303e37'; ctx.fillRect(-5, -11, 14, 22); ctx.fillStyle = '#6b796d'; ctx.fillRect(-2, -8, 8, 6); ctx.fillRect(-2, 3, 8, 6); ctx.fillStyle = '#27342f'; ctx.beginPath(); ctx.arc(-6, 0, 10, 0, 7); ctx.fill(); ctx.strokeStyle = team; ctx.lineWidth = 2; ctx.stroke(); ctx.fillStyle = '#141d1f'; ctx.fillRect(-1, -7, 5, 14); ctx.fillStyle = '#171d1d'; ctx.fillRect(9, -4, 36, 8); ctx.fillStyle = '#65706b'; ctx.fillRect(17, -6, 14, 4); ctx.fillStyle = '#111'; ctx.fillRect(39, -2, 10, 4); ctx.restore(); if (s.invuln > 0) { ctx.strokeStyle = '#ffffff66'; ctx.lineWidth = 2; ctx.beginPath(); ctx.arc(s.x, s.y, 22, 0, 7); ctx.stroke(); } ctx.fillStyle = '#1a2525'; ctx.fillRect(s.x - 22, s.y - 33, 44, 5); ctx.fillStyle = team; ctx.fillRect(s.x - 22, s.y - 33, 44 * s.hp / 100, 5); ctx.fillStyle = '#fff'; ctx.font = '11px Arial'; ctx.textAlign = 'center'; ctx.fillText(s.id, s.x, s.y - 40); }
function draw() { ctx.clearRect(0, 0, CW, CH); ctx.save(); ctx.translate(-camera.x, -camera.y); drawMap(); for (const s of soldiers) drawSoldier(s); for (const b of bullets) { ctx.strokeStyle = b.team === 'blue' ? '#a5ddff' : '#ffb0a3'; ctx.lineWidth = 3; ctx.beginPath(); ctx.moveTo(b.x, b.y); ctx.lineTo(b.x - b.vx * .018, b.y - b.vy * .018); ctx.stroke(); } for (const e of effects) { ctx.fillStyle = e.type === 'flash' ? '#ffe9a1' : '#f0c577'; ctx.beginPath(); ctx.arc(e.x, e.y, e.type === 'flash' ? 8 : 4, 0, 7); ctx.fill(); } ctx.restore(); drawMini(); }
function drawMini() { mc.clearRect(0, 0, 180, 120); mc.fillStyle = '#3a4643'; mc.fillRect(0, 0, 180, 120); const sx = 180 / W, sy = 120 / H; mc.fillStyle = '#82908c'; for (const w of walls) mc.fillRect(w.x * sx, w.y * sy, Math.max(1, w.w * sx), Math.max(1, w.h * sy)); for (const s of soldiers) { if (s.hp <= 0) continue; mc.fillStyle = color(s.team); mc.beginPath(); mc.arc(s.x * sx, s.y * sy, s.human ? 3.5 : 2, 0, 7); mc.fill(); } mc.strokeStyle = '#fff8'; mc.strokeRect(camera.x * sx, camera.y * sy, CW * sx, CH * sy); }
function scoreBoard() { const rows = [...soldiers].sort((a, b) => a.team.localeCompare(b.team) || b.kills - a.kills); $('scoreRows').innerHTML = '<div><b>PLAYER</b><b>TEAM</b><b>KILLS</b><b>DEATHS</b></div>' + rows.map(s => `<div class="${s.team}"><span>${s.id}</span><span>${s.team.toUpperCase()}</span><span>${s.kills}</span><span>${s.deaths}</span></div>`).join(''); }
function frame(t) { const dt = Math.min(.033, (t - last) / 1000 || 0); last = t; if (mode === 'playing') update(dt); if (mode !== 'menu') draw(); requestAnimationFrame(frame); }
document.addEventListener('keydown', e => { const k = e.key.toLowerCase(); keys[k] = true; if ([' ', 'tab', 'control'].includes(k)) e.preventDefault(); if (k === 'tab' && mode === 'playing') { scoreBoard(); $('scoreboard').classList.remove('hidden'); } if (k === 'escape') { if (mode === 'playing') { mode = 'paused'; $('pause').classList.remove('hidden'); mouse.down = false; } else if (mode === 'paused') { mode = 'playing'; $('pause').classList.add('hidden'); } } if (mode === 'playing') { if (k === 'r') reload(player); if (k === '1') switchGun(player, 'rifle'); if (k === '2') switchGun(player, 'pistol'); } });
document.addEventListener('keyup', e => { keys[e.key.toLowerCase()] = false; if (e.key === 'Tab') $('scoreboard').classList.add('hidden'); });
canvas.addEventListener('mousemove', e => { const r = canvas.getBoundingClientRect(); mouse.x = (e.clientX - r.left) * CW / r.width; mouse.y = (e.clientY - r.top) * CH / r.height; $('reticle').style.left = (mouse.x / CW * 100) + '%'; $('reticle').style.top = (mouse.y / CH * 100) + '%'; }); canvas.addEventListener('mousedown', e => { if (e.button === 0) mouse.down = true; }); window.addEventListener('mouseup', () => { mouse.down = false; shotHeld = false; }); window.addEventListener('blur', () => { mouse.down = false; for (const k in keys) keys[k] = false; }); canvas.addEventListener('contextmenu', e => e.preventDefault());
$('play').onclick = start; $('again').onclick = start; $('resume').onclick = () => { mode = 'playing'; $('pause').classList.add('hidden'); }; function home() { mode = 'menu'; $('menu').classList.remove('hidden'); $('pause').classList.add('hidden'); $('results').classList.add('hidden'); $('hud').classList.add('hidden'); mouse.down = false; } $('quit').onclick = home; $('home').onclick = home;
requestAnimationFrame(frame);
